# Generated by Django 6.0.5 on 2026-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_normalize_request_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='documentation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
