# Generated by Django 6.0.5 on 2026-06-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_vnd_equipment_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='class_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='faculty',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='major',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='study_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
